
export const GET_MESSAGES = 'GET_MESSAGES'
export const SUCCESS_GETTING_MSGS = 'SUCCESS_GETTING_MSGS'
export const ERROR_GETTING_MSGS = 'ERROR_GETTING_MSGS'

export const SENDING_MSG = 'SENDING_MSG'
export const SUCCESS_SENDING_MSG = 'SUCCESS_SENDING_MSG'
export const ERROR_SENDING_MSG = 'ERROR_SENDING_MSG'
